"""initial schema

Revision ID: f6b1a312fd00
Revises: 
Create Date: 2026-07-04 21:57:49.897805+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b1a312fd00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)

    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.Column('director', sa.String(length=128), nullable=True),
    sa.Column('artist', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size_gb', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('cover_path', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('tags', sa.String(length=256), nullable=True),
    sa.Column('times_copied', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalog_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalog_entries_title'), ['title'], unique=False)

    op.create_table('configuration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section', 'key', name='uq_configuration_section_key')
    )
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_section'), ['section'], unique=False)

    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_logs_created_at'), ['created_at'], unique=False)

    op.create_table('key_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('key_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_values_key'), ['key'], unique=True)

    op.create_table('membership_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('min_visits', sa.Integer(), nullable=False),
    sa.Column('min_gb', sa.Float(), nullable=False),
    sa.Column('min_spent', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pc_datetime_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moment', sa.DateTime(timezone=True), nullable=False),
    sa.Column('to', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pc_datetime_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pc_datetime_changes_moment'), ['moment'], unique=False)

    op.create_table('removed_drives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('removal_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('root_directory', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('removed_drives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_removed_drives_removal_date_time'), ['removal_date_time'], unique=False)

    op.create_table('report_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alive_date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usb_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('vid', sa.String(length=16), nullable=True),
    sa.Column('pid', sa.String(length=16), nullable=True),
    sa.Column('total_capacity', sa.BigInteger(), nullable=True),
    sa.Column('connection_type', sa.String(length=16), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('is_known', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usb_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usb_devices_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_usb_devices_serial_number'), ['serial_number'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inactive', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('photo_path', sa.String(length=512), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('total_gb_copied', sa.Float(), nullable=False),
    sa.Column('first_visit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_visit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['usb_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('inserted_drives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insertion_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('space_bytes', sa.BigInteger(), nullable=True),
    sa.Column('available_space_bytes', sa.BigInteger(), nullable=True),
    sa.Column('available_space_bytes_at_the_end', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('root_directory', sa.String(length=255), nullable=True),
    sa.Column('volume_label', sa.String(length=255), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('is_mobile', sa.Boolean(), nullable=False),
    sa.Column('is_mounted_folder', sa.Boolean(), nullable=False),
    sa.Column('payment', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('comment_fixed', sa.Text(), nullable=True),
    sa.Column('previous_insertions_counter', sa.Integer(), nullable=False),
    sa.Column('previous_payments_sum', sa.Integer(), nullable=False),
    sa.Column('row_color', sa.Integer(), nullable=False),
    sa.Column('removed_drive_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('usb_device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['removed_drive_id'], ['removed_drives.id'], ),
    sa.ForeignKeyConstraint(['usb_device_id'], ['usb_devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inserted_drives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inserted_drives_insertion_date_time'), ['insertion_date_time'], unique=False)
        batch_op.create_index('ix_inserted_drives_serial_insertion', ['serial_number', 'insertion_date_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_inserted_drives_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_inserted_drives_usb_device_id'), ['usb_device_id'], unique=False)

    op.create_table('rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('reward_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['usb_devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rewards_device_id'), ['device_id'], unique=False)

    op.create_table('usb_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('drive_letter', sa.String(length=4), nullable=True),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('filesystem', sa.String(length=32), nullable=True),
    sa.Column('total_capacity', sa.BigInteger(), nullable=True),
    sa.Column('free_capacity_at_connect', sa.BigInteger(), nullable=True),
    sa.Column('free_capacity_at_disconnect', sa.BigInteger(), nullable=True),
    sa.Column('port', sa.String(length=64), nullable=True),
    sa.Column('speed', sa.String(length=32), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('files_copied', sa.Integer(), nullable=False),
    sa.Column('files_deleted', sa.Integer(), nullable=False),
    sa.Column('files_modified', sa.Integer(), nullable=False),
    sa.Column('bytes_copied', sa.BigInteger(), nullable=False),
    sa.Column('operation_count', sa.Integer(), nullable=False),
    sa.Column('avg_speed_mbps', sa.Float(), nullable=True),
    sa.Column('max_speed_mbps', sa.Float(), nullable=True),
    sa.Column('count_video', sa.Integer(), nullable=False),
    sa.Column('count_movie', sa.Integer(), nullable=False),
    sa.Column('count_series', sa.Integer(), nullable=False),
    sa.Column('count_music', sa.Integer(), nullable=False),
    sa.Column('count_document', sa.Integer(), nullable=False),
    sa.Column('count_image', sa.Integer(), nullable=False),
    sa.Column('count_game', sa.Integer(), nullable=False),
    sa.Column('count_app', sa.Integer(), nullable=False),
    sa.Column('count_other', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['usb_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usb_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usb_sessions_connected_at'), ['connected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usb_sessions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usb_sessions_disconnected_at'), ['disconnected_at'], unique=False)

    op.create_table('vip_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('vip_type', sa.String(length=16), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['usb_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('billings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('pricing_mode', sa.String(length=16), nullable=True),
    sa.Column('suggested_price', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('tax_percent', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('charged', sa.Float(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('not_charged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['usb_devices.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['usb_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_billings_device_id'), ['device_id'], unique=False)

    op.create_table('copies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('copy_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('full_path', sa.String(length=1024), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('inserted_drive_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['inserted_drive_id'], ['inserted_drives.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['usb_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copies_copy_date_time'), ['copy_date_time'], unique=False)
        batch_op.create_index('ix_copies_date_ext', ['copy_date_time', 'extension'], unique=False)
        batch_op.create_index(batch_op.f('ix_copies_extension'), ['extension'], unique=False)
        batch_op.create_index(batch_op.f('ix_copies_inserted_drive_id'), ['inserted_drive_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_copies_session_id'), ['session_id'], unique=False)

    op.create_table('deletions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deletion_date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('full_path', sa.String(length=1024), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('inserted_drive_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inserted_drive_id'], ['inserted_drives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deletions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deletions_deletion_date_time'), ['deletion_date_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletions_extension'), ['extension'], unique=False)
        batch_op.create_index(batch_op.f('ix_deletions_inserted_drive_id'), ['inserted_drive_id'], unique=False)

    op.create_table('file_operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('file_ext', sa.String(length=16), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['usb_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_operations_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_operations_session_id'), ['session_id'], unique=False)

    op.create_table('payment_alterations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('previous_payment', sa.Integer(), nullable=True),
    sa.Column('new_payment', sa.Integer(), nullable=True),
    sa.Column('alteration_date_time', sa.DateTime(), nullable=False),
    sa.Column('inserted_drive_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inserted_drive_id'], ['inserted_drives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_alterations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_alterations_alteration_date_time'), ['alteration_date_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_alterations_inserted_drive_id'), ['inserted_drive_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_alterations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_alterations_inserted_drive_id'))
        batch_op.drop_index(batch_op.f('ix_payment_alterations_alteration_date_time'))

    op.drop_table('payment_alterations')
    with op.batch_alter_table('file_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_operations_session_id'))
        batch_op.drop_index(batch_op.f('ix_file_operations_detected_at'))

    op.drop_table('file_operations')
    with op.batch_alter_table('deletions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deletions_inserted_drive_id'))
        batch_op.drop_index(batch_op.f('ix_deletions_extension'))
        batch_op.drop_index(batch_op.f('ix_deletions_deletion_date_time'))

    op.drop_table('deletions')
    with op.batch_alter_table('copies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copies_session_id'))
        batch_op.drop_index(batch_op.f('ix_copies_inserted_drive_id'))
        batch_op.drop_index(batch_op.f('ix_copies_extension'))
        batch_op.drop_index('ix_copies_date_ext')
        batch_op.drop_index(batch_op.f('ix_copies_copy_date_time'))

    op.drop_table('copies')
    with op.batch_alter_table('billings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billings_device_id'))
        batch_op.drop_index(batch_op.f('ix_billings_created_at'))

    op.drop_table('billings')
    op.drop_table('vip_entries')
    with op.batch_alter_table('usb_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usb_sessions_disconnected_at'))
        batch_op.drop_index(batch_op.f('ix_usb_sessions_device_id'))
        batch_op.drop_index(batch_op.f('ix_usb_sessions_connected_at'))

    op.drop_table('usb_sessions')
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rewards_device_id'))

    op.drop_table('rewards')
    with op.batch_alter_table('inserted_drives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inserted_drives_usb_device_id'))
        batch_op.drop_index(batch_op.f('ix_inserted_drives_serial_number'))
        batch_op.drop_index('ix_inserted_drives_serial_insertion')
        batch_op.drop_index(batch_op.f('ix_inserted_drives_insertion_date_time'))

    op.drop_table('inserted_drives')
    op.drop_table('clients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('usb_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usb_devices_serial_number'))
        batch_op.drop_index(batch_op.f('ix_usb_devices_alias'))

    op.drop_table('usb_devices')
    op.drop_table('service_sessions')
    op.drop_table('report_records')
    with op.batch_alter_table('removed_drives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_removed_drives_removal_date_time'))

    op.drop_table('removed_drives')
    with op.batch_alter_table('pc_datetime_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pc_datetime_changes_moment'))

    op.drop_table('pc_datetime_changes')
    op.drop_table('notifications')
    op.drop_table('membership_levels')
    with op.batch_alter_table('key_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_values_key'))

    op.drop_table('key_values')
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_logs_created_at'))

    op.drop_table('error_logs')
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_section'))
        batch_op.drop_index(batch_op.f('ix_configuration_key'))

    op.drop_table('configuration')
    with op.batch_alter_table('catalog_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_entries_title'))
        batch_op.drop_index(batch_op.f('ix_catalog_entries_category'))

    op.drop_table('catalog_entries')
    op.drop_table('backup_records')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
